import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ClientProvider } from "@/components/QueryClientProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "JobSphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full light">
      <ClientProvider>
        <body className={`${inter.className} h-full antialiased`}>
          <NuqsAdapter>{children}</NuqsAdapter>
          <Toaster richColors closeButton theme="light" />
        </body>
      </ClientProvider>
    </html>
  );
}
